alias amake='ndk-build'
alias fcpp='find . -type f -name "*.cpp" | xargs grep'
alias fc='find . -type f -name "*.c" | xargs grep'
alias fh='find . -type f -name "*.h" | xargs grep'
alias cg='cat log/A.log | grep fhw > tmp'
